# Generated by Django 5.2.5 on 2025-08-23 15:40

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="enrollment",
            options={"ordering": ["-enrollment_date"]},
        ),
        migrations.AlterModelOptions(
            name="instructor",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="enrollment_date",
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("F", "F"),
                    ("NA", "Not Applicable"),
                ],
                default="NA",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "course"], name="students_en_student_dc805c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "course"), name="unique_student_course"
            ),
        ),
    ]
