# Generated by Django 5.2.5 on 2025-08-23 15:45

import students.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_course_options_alter_enrollment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[students.validators.validate_score],
            ),
        ),
    ]
