# Generated by Django 5.2.5 on 2025-08-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_enrollment_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="grade",
            field=models.CharField(
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("F", "F"),
                    ("NA", "Not Applicable"),
                ],
                default="NA",
                max_length=2,
            ),
        ),
    ]
