# Generated by Django 5.2.5 on 2025-08-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metadata",
            options={"ordering": ["key"]},
        ),
        migrations.AlterField(
            model_name="metadata",
            name="key",
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name="metadata",
            index=models.Index(
                fields=["key", "value"], name="common_meta_key_602eec_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="metadata",
            constraint=models.UniqueConstraint(
                fields=("key", "value"), name="unique_key_value"
            ),
        ),
    ]
