name: Django CI

on:
  push:
    branches: [ main, devel ]
  pull_request:
    branches: [ main, devel ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DJANGO_SETTINGS_MODULE: core.settings
      DEBUG: False 
      SECRET_KEY: )zq*36xw*o6i+)e0__rj6u_l7n&9-=v-9nv^*&+6z32lqgmz!( 
      DB_PASSWORD: postgres
      DB_USER: postgres 
      DB_NAME: test_db
      DB_PORT: 5432 
      DB_HOST: localhost 
      ALLOWED_HOSTS: "localhost," 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/prod.txt
          # pip install -r dev-requirements.txt  # optional

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test
